### ISSUE TITLE
Separating consecutive messages

### ISSUE THREAD

**Issue by majidit** [QueraTeam/mattermost-chat-ui#4]
Hello and politeness
Thank you for your beautiful plugin
It would be much better if it could not be shown in a box and separated when we send several messages in a row.

@mjnaderi  @HamadTheIronside @mjafari98

**Comment by majidit** [comment]
Please consider this ....

**Comment by mjnaderi** [comment]
Hi.

Check out the latest release: https://github.com/QueraTeam/mattermost-chat-ui/releases/tag/v0.2.0

**Comment by majidit** [comment]
Thank You ....
